"""Criação das tabelas: cliente_novos, condicoes_pagamentos, item_codigos, itens, pagamentos, pre_venda_itens, pre_vendas, recebimentos e xmls.

Revision ID: 1405f69f7965
Revises: b793ba120ce2
Create Date: 2026-03-04 10:18:41.919222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1405f69f7965'
down_revision: Union[str, Sequence[str], None] = 'b793ba120ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente_novos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('bairro_id', sa.Integer(), nullable=True),
    sa.Column('cidade_id', sa.Integer(), nullable=True),
    sa.Column('cpf_cnpj', sa.String(), nullable=True),
    sa.Column('rg_ie', sa.String(), nullable=True),
    sa.Column('fone', sa.String(), nullable=True),
    sa.Column('celular', sa.String(), nullable=True),
    sa.Column('nome_fantasia', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('sexo', sa.Numeric(precision=1, scale=0), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('limite_credito', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fisica_juridica', sa.Numeric(precision=1, scale=0), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('condicoes_pagamentos',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('tipo_id', sa.Integer(), nullable=True),
    sa.Column('dias', sa.Numeric(precision=3, scale=0), nullable=True),
    sa.Column('vezes_max', sa.Numeric(precision=3, scale=0), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('empresa_id', 'id')
    )
    op.create_table('item_codigos',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('ean_gtin', sa.String(), nullable=False),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('empresa_id', 'item_id', 'ean_gtin')
    )
    op.create_table('itens',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('permitir_desconto', sa.Boolean(), nullable=True),
    sa.Column('nome_grupo', sa.String(), nullable=True),
    sa.Column('nome_subgrupo', sa.String(), nullable=True),
    sa.Column('nome_classe', sa.String(), nullable=True),
    sa.Column('sigla', sa.String(), nullable=True),
    sa.Column('preco_custo', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('preco_zero', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('preco_venda', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('preco_promocao', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('preco_pmc', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('saldo_estoque', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('desconto_maximo', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('data_fim_promocao', sa.Date(), nullable=True),
    sa.Column('data_inicio_promocao', sa.Date(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('empresa_id', 'id')
    )
    op.create_table('pagamentos',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('data_movimento', sa.Date(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('empresa_id', 'data_movimento', 'nome')
    )
    op.create_table('pre_venda_itens',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('pre_venda_id', sa.Integer(), nullable=False),
    sa.Column('sequencia', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('valor_venda', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('valor_promocao', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('valor_desconto', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('empresa_id', 'pre_venda_id', 'sequencia')
    )
    op.create_table('pre_vendas',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('condicao_pagamento_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_movimento', sa.Date(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('disk_entrega', sa.Boolean(), nullable=True),
    sa.Column('enviado', sa.Boolean(), nullable=True),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('ide_mobile', sa.String(), nullable=True),
    sa.Column('qtd_vezes', sa.Numeric(precision=2, scale=0), nullable=True),
    sa.PrimaryKeyConstraint('empresa_id', 'id')
    )
    op.create_table('recebimentos',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('data_movimento', sa.Date(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('empresa_id', 'data_movimento', 'nome')
    )
    op.create_table('xmls',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.Numeric(precision=2, scale=0), nullable=True),
    sa.Column('serie', sa.Numeric(precision=2, scale=0), nullable=True),
    sa.Column('numero', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('chave_xml', sa.String(), nullable=True),
    sa.Column('xml', sa.Text(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_movimento', sa.Date(), nullable=True),
    sa.Column('entrada_saida', sa.Numeric(precision=1, scale=0), nullable=True),
    sa.PrimaryKeyConstraint('empresa_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xmls')
    op.drop_table('recebimentos')
    op.drop_table('pre_vendas')
    op.drop_table('pre_venda_itens')
    op.drop_table('pagamentos')
    op.drop_table('itens')
    op.drop_table('item_codigos')
    op.drop_table('condicoes_pagamentos')
    op.drop_table('cliente_novos')
    # ### end Alembic commands ###
