"""Adicionada tabela de Pessoas

Revision ID: a7c38e7dee28
Revises: d5becf594190
Create Date: 2026-03-02 09:40:19.466901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7c38e7dee28'
down_revision: Union[str, Sequence[str], None] = 'd5becf594190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pessoas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fisica_juridica', sa.NUMERIC(precision=1, scale=0), autoincrement=False, nullable=True),
    sa.Column('cpf_cnpj', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_cadastro', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('limite_credito', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('rg_ie', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('sexo', sa.NUMERIC(precision=1, scale=0), autoincrement=False, nullable=True),
    sa.Column('credito_encerrado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('mae', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vendedor_codigo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_registro', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('qtd_dupl_pagas', sa.NUMERIC(precision=8, scale=0), autoincrement=False, nullable=True),
    sa.Column('qtd_dupl_atrasadas', sa.NUMERIC(precision=8, scale=0), autoincrement=False, nullable=True),
    sa.Column('qtd_dupl_avencer', sa.NUMERIC(precision=8, scale=0), autoincrement=False, nullable=True),
    sa.Column('total_pago', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_atrasado', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_avencer', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('dias_maior_atraso', sa.NUMERIC(precision=8, scale=0), autoincrement=False, nullable=True),
    sa.Column('dias_maior_avencer', sa.NUMERIC(precision=8, scale=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('empresa_id', 'id', name=op.f('pessoas_idx'))
    )
    # ### end Alembic commands ###
