"""Add tabela Pessoa_Contatos

Revision ID: b793ba120ce2
Revises: e81a788f3c00
Create Date: 2026-03-03 11:31:34.303322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b793ba120ce2'
down_revision: Union[str, Sequence[str], None] = 'e81a788f3c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
