"""initial

Revision ID: d5becf594190
Revises: 
Create Date: 2026-02-24 10:32:11.698848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5becf594190'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_cnpj', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('cpf_contabilista', sa.String(), nullable=True),
    sa.Column('contador', sa.Boolean(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('razao_social', sa.String(), nullable=True),
    sa.Column('celular_ativo', sa.Boolean(), nullable=True),
    sa.Column('disk_entrega_item_id', sa.Numeric(precision=14, scale=0), nullable=True),
    sa.Column('data_ultimo_acesso', sa.Date(), nullable=True),
    sa.Column('qtd_bulas', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('qtd_imagens', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_integra',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('consultar_pessoas', sa.String(), nullable=True),
    sa.Column('consultar_itens', sa.String(), nullable=True),
    sa.Column('consultar_faturamentos', sa.String(), nullable=True),
    sa.Column('consultar_recebimentos', sa.String(), nullable=True),
    sa.Column('efetuar_pre_vendas', sa.String(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('consultar_pagamentos', sa.String(), nullable=True),
    sa.Column('desconto_maximo', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('digitar_preco_venda', sa.String(), nullable=True),
    sa.Column('gerar_gordura_precos', sa.String(), nullable=True),
    sa.Column('total_gordura', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('empresa_id', 'usuario')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('sabor', sa.String(), nullable=True),
    sa.Column('tamanho', sa.String(), nullable=True),
    sa.Column('preco_unitario', sa.Float(), nullable=True),
    sa.Column('pedido', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_pedido')
    op.drop_table('pedidos')
    op.drop_table('usuarios_integra')
    op.drop_table('usuarios')
    op.drop_table('empresas')
    # ### end Alembic commands ###
